---
# defaults file for nginx
# nginx templates
nginx_conf_template: "nginx.conf.j2"
nginx_vhost_template: "vhost.j2"
nginx_ssl_template: "ssl.conf.j2"
nginx_srv_conf_template: "service.conf.j2"

# Nginx package version, like 1.22.1-9, 1.18.0, 1.18.0-1~buster or 1.18*.
# Only possible upgrade version from old to new.
# -----------------------------------------------------------------------
# When provide required nginx_package_version, then:
#   if nginx package is present on target host and it has required version - nothing to do
#   else if nginx package is present on target host and it has lower version, then upgrade to required
#   else if nginx package is present on target host and it has higher version - downgrade is not allowed
#   else if nginx package is absent on target host - install required version.
# -----------------------------------------------------------------------
# When provide nginx_package_version: latest, then:
#   if nginx package is present on target host and it has latest version - nothing to do
#   else if nginx package is present on target host and it has lower version, than latest - upgrade package version to latest
#   else if nginx package is absent on target host - install latest version
#   else if nginx package is not defined - install latest version
# -----------------------------------------------------------------------
# When nginx_package_version is not define, then install latest version on Nginx package
nginx_package_version: latest

# nginx configuration
nginx_worker_processes: "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_gzip: "on"

nginx_server_tokens: "on"

nginx_client_max_body_size: "64m"

nginx_server_names_hash_bucket_size: "64"

nginx_proxy_cache_path: ""

nginx_charset: ""

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

nginx_remove_default_vhost: false

# nginx vhost configuration
nginx_vhosts: []
# Example vhost below, showing all available options:
# - listen: "80" # default: "80"
#   state: "absent" # To remove the vhost configuration.
#   server_name: "example.com" # default: N/A
#   root: "/var/www/example.com" # default: N/A
#   index: "index.html index.htm" # default: N/A
#   filename: "example.com.conf" # Can be used to set the vhost filename.
#
#   # Properties that are only added if defined:
#   server_name_redirect: "www.example.com" # default: N/A
#   error_page: ""
#   access_log: ""
#   error_log: ""
#   extra_parameters: "" # Can be used to add extra config blocks (multiline).
#   template: "" # Can be used to override the `nginx_vhost_template` per host.
#

nginx_snippets: {}
# Adds nginx snippets
# Example:
#   nginx_snippets:
#     snippet_name1.conf: |
#       multistring
#       snippet
#       content
#     snippet_name2.conf: |
#       multistring
#       snippet
#       content

use_ssl: false
# Enable ssl configuration

nginx_ssl: []
# Example ssl configuration
# - ssl_certificate: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
#   ssl_certificate_key: "/etc/ssl/private/ssl-cert-snakeoil.key"
#   ssl_trusted_certificate: "/etc/ssl/ca.crt"

nginx_upstreams: []
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   keepalive: 16 # optional
#   servers: {
#     "srv1.example.com",
#     "srv2.example.com weight=3",
#     "srv3.example.com"
#   }

nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'

nginx_install_modules: false
# install modules from repository

nginx_modules: []
# - http-fancyindex

nginx_custom_srv_conf: |-
# Example of additional options for nginx.service
#   [Service]
#   LimitNOFILE=8192
#   LimitNOFILESoft=4096
